annotations:
  catalog.cattle.io/display-name: Clock Ext
  catalog.cattle.io/certified: rancher # Any application we are adding as a helm chart
  catalog.cattle.io/kube-version: '>= 1.16.0-0 < 1.25.0-0'
  catalog.cattle.io/namespace: cattle-ui-plugin-system # Must prefix with cattle- and suffix with -system=
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux, windows
  catalog.cattle.io/rancher-version: '>= 2.7.0-0 < 2.8.0-0'
  catalog.cattle.io/scope: management
  catalog.cattle.io/ui-component: plugins
apiVersion: v2
appVersion: "0.2.0"
description: Adds a new feature to the top-level menu that shows a full-page clock
name: clock
type: application
version: 0.2.0
icon: https://raw.githubusercontent.com/rancher/ui-plugin-examples/main/pkg/clock/clock.svg
